### ISSUE TITLE
Didn't download messages of Supergroup

### ISSUE THREAD

**Issue by dominikviererbe** [fabianonline/telegram_backup#50] opened 2017-06-28 16:44 UTC
I had upgraded a telegram Group to a Supergroup. Within the sqlite db the Group is splitted in two Chats. One before the Group was a supergroup and one after the Group was upgraded, but the jar didn't downloaded the messeges after the Group was updated. Within the sqlite file there are no Messages from the supergroup.

**Comment by Hypfer** [comment] 2017-07-02 22:50
Yes.

**Comment by Lin0815** [comment] 2017-07-03 15:57
"Yes." means what?

**Comment by Hypfer** [comment] 2017-07-03 16:36
"Yes." means go use the search function before opening another issue on the same topic.

https://github.com/fabianonline/telegram_backup/issues/21

**Comment by fabianonline** [comment] 2017-11-26 11:16
Duplicate of #21. Closing this.

Just a quick heads-up: I'm currently actively working on this feature and expect a first test release to be available in just a few days.

**Closed by fabianonline** 2017-11-26 11:16 UTC
