### ISSUE TITLE
400: LOCATION_INVALID

### ISSUE THREAD

**Issue by ximocoder** [fabianonline/telegram_backup#55] opened 2017-08-07 08:57 UTC
Get this error when downloading the pictures, has downloaded half of them but at this one gets the error:
`.RpcErrorException happened while downloading C:\Users\ximo\.telegram_backup\+xxxxxxxxxxx\files\159321.png
400: LOCATION_INVALID
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:209)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries$default(DefaultTelegramClient.kt:181)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:160)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQueries(DefaultTelegramClient.kt:166)
        at com.github.badoualy.telegram.api.TelegramClient$DefaultImpls.executeRpcQuery(TelegramClient.kt:56)
        at com.github.badoualy.telegram.api.DefaultTelegramClient.executeRpcQuery(DefaultTelegramClient.kt:25)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFileFromDc(DownloadManager.java:330)
        at de.fabianonline.telegram_backup.DownloadManager.downloadFile(DownloadManager.java:300)
        at de.fabianonline.telegram_backup.mediafilemanager.DocumentFileManager.download(DocumentFileManager.java:105)
        at de.fabianonline.telegram_backup.DownloadManager._downloadMedia(DownloadManager.java:276)
        at de.fabianonline.telegram_backup.DownloadManager.downloadMedia(DownloadManager.java:229)
        at de.fabianonline.telegram_backup.CommandLineController.<init>(CommandLineController.java:173)
        at de.fabianonline.telegram_backup.CommandLineRunner.main(CommandLineRunner.java:77)`

it would be great to be able to ask for ignoring this file.

**Comment by fabianonline** [comment] 2018-03-07 17:16
Duplicate of #54.

**Closed by fabianonline** 2018-03-07 17:16 UTC
