### ISSUE TITLE
[FEATURE REQUEST] Media timestamps

### ISSUE THREAD

**Issue by shiksb** [fabianonline/telegram_backup#59] opened 2017-11-09 22:11 UTC
The media that is downloaded has no timestamp for when it was created. It would be really helpful if you could either include the timestamp of creation in the media filename, or update the metadata of the image to indicate the timestamp and creator.

**Comment by fabianonline** [comment] 2018-03-07 17:12
This is a duplicate of #81. I'll close this issue, but the feature will still come sometime.

**Closed by fabianonline** 2018-03-07 17:12 UTC
Labels: duplicate, feature
